=== dkill0/Documents/Lenguaje_de_marcas/carlos penalver/03_paises.dtd
<!ELEMENT paises (pais*)>
<!ELEMENT pais (superficie, moneda, gobierno, fronteras,idioma+)>
<!ATTLIST pais nombre ID #REQUIRED>
<!ELEMENT superficie (#PCDATA)>
<!ATTLIST superficie unidad NMTOKEN #REQUIRED>
<!ELEMENT moneda (#PCDATA)>
<!ELEMENT gobierno EMPTY>
<!ATTLIST gobierno sistema NMTOKEN #IMPLIED>
<!ELEMENT fronteras EMPTY>
<!ATTLIST fronteras pais IDREFS #IMPLIED>
<!ELEMENT idioma (#PCDATA)>

=== dkill0/Documents/Lenguaje_de_marcas/carlos penalver/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises SYSTEM "03_paises.dtd">
<paises>
    <pais nombre="ESP">
        <superficie unidad="km2">504.654</superficie>
        <moneda>euro</moneda>
        <gobierno sistema="monarquia" />
        <fronteras pais="FRA" />
        <idioma>Espa√±ol</idioma>
    </pais>
    <pais nombre="FRA">
        <superficie unidad="km2">675.417</superficie>
        <moneda>euro</moneda>
        <gobierno sistema="republica" />
        <fronteras pais="ESP SZA" />
        <idioma>Frances</idioma>
    </pais>
    <pais nombre="SZA">
        <superficie unidad="km2">41.290</superficie>
        <moneda>franco suizo</moneda>
        <gobierno sistema="republica" />
        <fronteras/>
        <idioma>frances, aleman, italiano y romanche</idioma>
    </pais>
</paises>
