=== dkill0/Documents/Lenguaje_de_marcas/carlos penalver/07_cine.dtd
<!ELEMENT cine (peliculas, salas)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, añoEstreno, actor)>
<!ATTLIST pelicula
          codigo ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT añoEstreno (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT salas (sala+)>
<!ELEMENT sala (nombre, peliculaEmitida, sesion)>
<!ATTLIST sala
          codSala ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT peliculaEmitida (#PCDATA)>
<!ATTLIST peliculaEmitida
          codigo IDREFS #REQUIRED>
<!ELEMENT sesion (#PCDATA)>

=== dkill0/Documents/Lenguaje_de_marcas/carlos penalver/07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine SYSTEM "07_cine.dtd">

<cine>
    <peliculas>
        <pelicula codigo="JOK">
            <titulo>Joker</titulo>
            <añoEstreno>2019</añoEstreno>
            <actor>Joaquin Phoenix</actor>
        </pelicula>
        <pelicula codigo="DARK">
            <titulo>"The Dark Knight"</titulo>
            <añoEstreno>2008</añoEstreno>
            <actor>Heath Ledger</actor>
        </pelicula>
        <pelicula codigo="BAT">
            <titulo>Batman</titulo>
            <añoEstreno>1989</añoEstreno>
            <actor>Jack Nicolson</actor>
        </pelicula>
    </peliculas>
    <salas>
        <sala codSala="S1">
            <nombre>Sala 1</nombre>
            <peliculaEmitida codigo="JOK"/>
            <sesion>16:00, 19:30, 22:00</sesion>
        </sala>
        <sala codSala="S2">
            <nombre>Sala 2</nombre>
            <peliculaEmitida codigo="DARK"/>
            <sesion>18:00, 21:30</sesion>
        </sala>
        <sala codSala="S3">
            <nombre>Sala 1</nombre>
            <peliculaEmitida codigo="BAT"/>
            <sesion>20:00, 22:30</sesion>
        </sala>
    </salas>


</cine>
