<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sedes [
<!ELEMENT sedes (francia, italia, dinamarca)>
<!ELEMENT francia (ciudad+)>
<!ELEMENT italia (ciudad+)>
<!ELEMENT dinamarca (ciudad+)>
<!ELEMENT ciudad (#PCDATA)>
]>
<sedes>
<francia>
<ciudad>paris</ciudad>
<ciudad>nantes</ciudad>
</francia>
<italia>
<ciudad>roma</ciudad>
<ciudad>florencia</ciudad>
<ciudad>venecia</ciudad>
</italia>
<dinamarca>
<ciudad>Copenhague</ciudad>
</dinamarca>
</sedes>