<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comidas [
<!ELEMENT comidas (comida)*>
<!ELEMENT comida ((codigo | nombre), precio)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
]>
<comidas>
<comida>

<nombre>salchicha</nombre>
<precio>6</precio>
</comida>
<comida>
<codigo></codigo>
<precio>8</precio>
</comida>
</comidas>