=== dkill0/Documents/Lenguaje de marcas/XML/DTD ejercicios/listado.dtd
<!ELEMENT listado (persona)*>
<!ELEMENT persona (nombre, fecha_nacimiento, desempleado?)>
<!ELEMENT nombre (#PCDATA )>
<!ELEMENT fecha_nacimiento (#PCDATA )>
<!ELEMENT desempleado  EMPTY>

=== dkill0/Documents/Lenguaje de marcas/XML/DTD ejercicios/5b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listado SYSTEM "listado.dtd">
<listado>
<persona>
<nombre>Antonio López</nombre>
<fecha_nacimiento>28-02-2001</fecha_nacimiento>
<desempleado/>
</persona>
<persona>
<nombre>Amparo Pérez</nombre>
<fecha_nacimiento>21-06-2002</fecha_nacimiento>
</persona>
</listado>
